{{- if .Values.syslogSidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-iptables-tailer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-iptables-tailer.name" . }}
    helm.sh/chart: {{ include "kube-iptables-tailer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  rsyslog.conf: |
    module(load="imklog" ParseKernelTimestamp="on" KeepKernelTimestamp="off")
    template(name="traditional_with_rfc3339" type="string" string="%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n")
    $FileOwner rsyslog
    $FileGroup rsyslog
    $FileCreateMode 0640
    $DirCreateMode 0755
    $Umask 0022
    $WorkDirectory /work
    # drop everything that's not calico-packet
    :msg, !startswith, " calico-packet:" ~
    kern.* -/logs/kernel.log;traditional_with_rfc3339
{{- end }}
