{{- if .Values.ingress.enabled -}}
{{- $fullName := include "squid.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: {{ include "squid.ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "squid.name" . }}
    chart: {{ template "squid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if eq (include "squid.ingress.apiVersion" $) "networking.k8s.io/v1" }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
            {{- if eq (include "squid.ingress.apiVersion" $) "networking.k8s.io/v1" }}
              service:
                name: {{ $fullName }}
                port:
                  name: http
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: http
            {{- end }}
  {{- end }}
{{- end }}
