---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "looker.fullname" . }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager-infra
    kind: ClusterSecretStore
  data:
    - secretKey: database_pass
      remoteRef:
        key: {{ .Values.database.secret_store_key_arn }}
        property: looker/database_pass
  target:
    name: {{ include "looker.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Merge
    template:
      data:
        looker-db.yml: |-
          dialect: {{ .Values.database.dialect }}
          host: {{ .Values.database.host }}
          username: {{ .Values.database.username }}
          password: {{ "{{" }} .database_pass {{ "}}" }}
          database: {{ .Values.database.database }}
          port: {{ .Values.database.port }}
          jdbc_additional_params: useSsl=true&serverSslCert=/certs/db_server_cert.pem
