{{- if .Values.ingressHealthcheck.enabled -}}
{{- $fullName := include "looker.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-healthcheck
  labels:
    {{- include "looker.labels" . | nindent 4 }}
  {{- with .Values.ingressHealthcheck.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressHealthcheck.tls }}
  tls:
    {{- range .Values.ingressHealthcheck.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressHealthcheck.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /alive
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 443
    {{- end }}
  {{- end }}
