{{- if .Values.networkPolicies.enabled }}
# https://docs.looker.com/setup-and-management/on-prem-install/outbound-ports
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "looker.fullname" . }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "looker.selectorLabels" . | nindent 6 }}
  egress:
{{- if .Values.networkPolicies.tooling.enabled }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 169.254.0.0/16
        - 172.16.0.0/12
        - 192.168.0.0/16
    ports:
    # sentry
    - protocol: TCP
      port: 9000
    # ping.looker.com / license.looker.com
    - protocol: UDP
      port: 443
    # user email sending
    - protocol: TCP
      port: 587
    # git
    - protocol: TCP
      port: 9418
    # sftp || github via ssh
    - protocol: TCP
      port: 22
{{- end }}
{{- if .Values.networkPolicies.dbRanges }}
{{- if .Values.networkPolicies.dbRanges.mysql }}
  - to:
    {{- range .Values.networkPolicies.dbRanges.mysql }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 3306
{{- end }}
{{- if .Values.networkPolicies.dbRanges.postgres }}
  - to:
    {{- range .Values.networkPolicies.dbRanges.postgres }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 5432
{{- end }}
{{- end }}
  policyTypes:
  - Egress
{{- end }}
