{{- if .Values.databaseConfigFile -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "looker.fullname" . }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
type: Opaque
stringData:
  looker-db.yml: |
    {{ .Values.databaseConfigFile | nindent 4 }}
{{ end }}
