version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    environment:
      HELM_VERSION: 3.18.6
      CONFTEST_VERSION: 0.62.0
    steps:
      - checkout
      - run:
          name: setup helm
          command: curl -SL https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar xvz -C /tmp && sudo chmod +x /tmp/linux-amd64/* && sudo mv /tmp/linux-amd64/* /usr/local/bin/
      - run:
          name: Execute lint on the charts
          command: |
            helm lint ./kube-iptables-tailer -f examples/kube-iptables-tailer/values.yaml
            helm lint ./squid -f examples/squid/values.yaml
            helm lint ./looker -f examples/looker/values.yaml
      - run:
          name: Execute helm template
          command: |
            helm template ./kube-iptables-tailer -f examples/kube-iptables-tailer/values.yaml > kube-iptables-tailer.yaml
            helm template ./squid -f examples/squid/values.yaml > squid.yaml
            helm template ./looker -f examples/looker/values.yaml > looker.yaml

  release:
    environment:
      HELM_VERSION: 3.18.6
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install helm
          command: |
            curl -SL https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar xvz -C /tmp && sudo chmod +x /tmp/linux-amd64/* && sudo mv /tmp/linux-amd64/* /usr/local/bin/
      - add_ssh_keys:
          fingerprints:
            - "96:6f:38:13:f5:a6:18:05:d4:0f:b4:0f:f5:62:e5:2b"
      - run:
          name: Package and index doc
          command: |
            git config user.email "ops@lifen.fr"
            git config user.name "Lifen"
            git fetch origin
            git checkout -b release
            git checkout gh-pages
            git merge release  --no-edit
            helm package kube-iptables-tailer -d packages
            helm package squid -d packages
            helm package looker -d packages
            helm repo index packages --url https://honestica.github.io/lifen-charts/packages
            mv packages/index.yaml index.yaml
            cp packages/artifacthub-repo.yml artifacthub-repo.yml
      - run:
          name: Push to repo
          command: |
            git add packages index.yaml artifacthub-repo.yml
            git commit -m "relase version"
            git push origin gh-pages

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
                - master
          context: org-global
      - release:
          filters:
            branches:
              only: master
              ignore: gh-pages
