apiVersion: v1
appVersion: 2.16.0
description: A Looker Helm chart for Kubernetes.
home: https://github.com/honestica/lifen-charts
icon: https://looker.com/assets/img/images/logos/looker.svg
keywords:
- looker
- google
- data
maintainers:
- email: matthieu.paret@lifen.fr
  name: mparet
name: looker
sources:
- https://github.com/honestica/lifen-charts
- https://github.com/honestica/docker-looker
version: 0.1.8
