{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "op-scim-bridge.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "op-scim-bridge.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}